<?php if (! $compact): ?>
<div class="controls">
    <?= $tabs ?>
</div>
<?php endif ?>
<div class="content">
<?= $this->qlink(
    $this->translate('Create a New Announce') ,
    'announces/add',
    null,
    array(
        'class'             => 'button-link',
        'data-base-target'  => '_next',
        'icon'              => 'plus',
        'title'             => $this->translate('Create a new announce')
    )
) ?>
<?php if (! $announces->hasResult()): ?>
    <p><?= $this->translate('No announces found.') ?></p>
</div>
<?php return; endif ?>
    <table data-base-target="_next" class="table-row-selectable common-table">
    <thead>
        <tr>
            <th><?= $this->translate('Author') ?></th>
            <th><?= $this->translate('Message') ?></th>
            <th><?= $this->translate('Start') ?></th>
            <th><?= $this->translate('End') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($announces as $announce): /** @var object $announce */ ?>
        <tr>
            <td><?= $this->escape($announce->author) ?></td>
            <td><?= $this->qlink(
                $this->ellipsis($announce->message, 100),
                'announces/edit',
                array('id' => $announce->id),
                array('title' => $this->translate('Edit this announce'))
            ) ?></td>
            <td><?= $this->formatDateTime($announce->start->getTimestamp()) ?></td>
            <td><?= $this->formatDateTime($announce->end->getTimestamp()) ?></td>
            <td class="icon-col"><?= $this->qlink(
                null,
                'announces/remove',
                array('id' => $announce->id),
                array(
                    'class' => 'action-link',
                    'icon'  => 'cancel',
                    'title' => $this->translate('Remove this announce')
                )
            ) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
</div>
